# -*- coding: utf-8 -*-
"""train_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ee0BZ8qK9ngjqMcTukPVxmN6dvN35qv0
"""

## train_model.py — AI Academic Advisor ##
## Run this once to train and save your model ##

## Import Libraries ##

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
import joblib
import os

## Load Dataset ##

df = pd.read_csv("data/student_data.csv")

## Check Data ##

df.info()
print("\nMissing values:\n", df.isnull().sum())

## Create Target Column (PASS / FAIL) ##

df['Result'] = df['Final Exam Marks (out of 100)'].apply(
    lambda x: 1 if x >= 50 else 0
)

df[['Final Exam Marks (out of 100)', 'Result']].head()

## Select Features ##

X = df[[
    'Attendance (%)',
    'Internal Test 1 (out of 40)',
    'Internal Test 2 (out of 40)',
    'Assignment Score (out of 10)',
    'Daily Study Hours'
]]

y = df['Result']

## Train/Test Split ##

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42
)

## Scale Data ##

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

## Train Model (LOGISTIC REGRESSION) ##

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

## Test Model ##

y_pred = model.predict(X_test_scaled)

print(y_pred[:10])

## Check Accuracy ##

accuracy = accuracy_score(y_test, y_pred)
print(f"\nAccuracy: {accuracy * 100:.1f}%")
print("\nDetailed report:\n", classification_report(y_test, y_pred))

## Save Model ##

os.makedirs("model", exist_ok=True)

joblib.dump(model, "model/student_model.pkl")
joblib.dump(scaler, "model/scaler.pkl")

print("Model and scaler saved to model/")