# -*- coding: utf-8 -*-
"""train_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ee0BZ8qK9ngjqMcTukPVxmN6dvN35qv0
"""

## Import Libraries ##

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression

from google.colab import files

import joblib
import io

## Select and Upload Dataset ##

uploaded = files.upload()

## Load Dataset ##

df = pd.read_csv(io.BytesIO(uploaded[list(uploaded.keys())[0]]))

df.head()

## Check Data ##

df.info()
df.isnull().sum()

## Create Target Column (PASS / FAIL) ##

df['Result'] = df['Final Exam Marks (out of 100)'].apply(
    lambda x: 1 if x >= 50 else 0
)

df[['Final Exam Marks (out of 100)', 'Result']].head()

## Select Features ##

X = df[[
    'Attendance (%)',
    'Internal Test 1 (out of 40)',
    'Internal Test 2 (out of 40)',
    'Assignment Score (out of 10)',
    'Daily Study Hours'
]]

y = df['Result']

## Scale Data ##

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

## Train/Test Split ##

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y,
    test_size=0.3,
    random_state=42
)

## Train Model (LOGISTIC REGRESSION) ##

model = LogisticRegression()
model.fit(X_train, y_train)

## Test Model ##

y_pred = model.predict(X_test)

print(y_pred[:10])

## Check Accuracy ##

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

## Save Model ##

joblib.dump(model, "student_model.pkl")
joblib.dump(scaler, "scaler.pkl")

## Download Model ##

files.download("student_model.pkl")
files.download("scaler.pkl")

print("Model Saved")